# Generated by Django 5.0.2 on 2024-04-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='follow',
        ),
    ]
