# Generated by Django 5.0.2 on 2024-05-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_commentreaction_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reaction', to='Post.post'),
        ),
    ]
