# Generated by Django 5.0.2 on 2024-04-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='p_address',
        ),
    ]
