# Generated by Django 5.0.2 on 2024-05-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follower',
        ),
    ]
