# Generated by Django 5.0.2 on 2024-05-01 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_following_delete_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('author', 'follower')},
        ),
    ]
